server:
  port: 9090
thymeleaf:
  cache: false
  prefix:  classpath:/templates/
  check-template-location: true
  suffix: .html
  encoding: utf-8
  mode: HTML
  #这个是关键，放开springboot对静态资源的拦截
mvc:
  static-path-pattern: /static/**

  #spring配置
spring:
  application:
    name: cloud-payment-service

  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/school_take_out?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  # mybatis配置
mybatis:
  mapper-locations: classpath:com.springboot.mapper/*.xml # mapper映射文件位置
  type-aliases-package: com.springboot.entity # 实体类所在的位置
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #用于控制台打印sql语句